# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses:
        - contracts@platinumtechsolutions.co.uk
    delivery_whitelist:
        # make sure that we can only email our domain on dev
        - '/@platinumtechsolutions\.co\.uk$/'
